---
title: "Interaction"
author: "Shylo Burrell"
date: "4/19/2021"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(janitor)
library(readxl)
library(data.table)
library(ggplot2)

clean_names <- janitor::clean_names
here <- here::here
source_path <- here("R/ggplotsci.R")
source(source_path)
data_folder <- "data"

```

```{r import interaction}

data_folder <- "factorial_design"
data_from <- "Interaction"
file_name <- "interaction - testing.xlsx"

```


```{r}

file_path <- here(data_folder, data_from, file_name)
interaction_data_table <- read_excel(file_path,
                    sheet = "Sheet1",
                    range = "B1:Q436") %>%
  clean_names()  %>%
  data.table()
  interaction_data <- interaction_data_table[c(5, 11, 18, 24, 26:29, 32:37, 40, 41, 43:45, 47, 49:54, 56:67, 71:81, 83:435),-c("jaw_tests", "comment")] #relevant rows & columns

#View(interaction_data)
  

```


```{r}
table(interaction_data$data_availability)
table(interaction_data$design)
table(interaction_data$analysis)
table(interaction_data$t_tests)
table(interaction_data$tests)
table(interaction_data$post_hoc)
table(interaction_data$ixn_reported)
```


```{r}

journal_vs_ixn_reported <- ggplot(data = interaction_data,
                             aes(x =  ixn_reported,
                                 y = journal,
                                 color = journal)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_jitter(width = 0.3, show.legend = FALSE) 

journal_vs_ixn_reported


```

```{r}
data_availability_vs_ixn_reported <- ggplot(data = interaction_data,
                             aes(x =  ixn_reported,
                                 y = data_availability,
                                 color = journal)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_jitter(width = 0.3, show.legend = FALSE) 

data_availability_vs_ixn_reported

```


```{r}

design_vs_ixn_reported <- ggplot(data = interaction_data,
                             aes(x =  ixn_reported,
                                 y = design,
                                 color = journal)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_jitter(width = 0.3, show.legend = FALSE) 

design_vs_ixn_reported

```


```{r}

analysis_vs_ixn_reported <- ggplot(data = interaction_data,
                             aes(x =  ixn_reported,
                                 y = analysis,
                                 color = journal)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_jitter(width = 0.3, show.legend = FALSE) 

analysis_vs_ixn_reported

```


```{r}

tests_vs_ixn_reported <- ggplot(data = interaction_data,
                             aes(x =  ixn_reported,
                                 y = tests,
                                 color = journal)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_jitter(width = 0.3, show.legend = FALSE) 

tests_vs_ixn_reported

```

```{r}

t_tests_vs_ixn_reported <- ggplot(data = interaction_data,
                             aes(x =  ixn_reported,
                                 y = t_tests,
                                 color = journal)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_jitter(width = 0.3, show.legend = FALSE) 

t_tests_vs_ixn_reported

```

```{r}

post_hoc_vs_ixn_reported <- ggplot(data = interaction_data,
                             aes(x =  ixn_reported,
                                 y = post_hoc,
                                 color = journal)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_jitter(width = 0.3, show.legend = FALSE) 

post_hoc_vs_ixn_reported
```


```{r}

journal_vs_data_availability <- ggplot(data = interaction_data,
                             aes(x =  data_availability,
                                 y = journal,
                                 color = journal)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_jitter(width = 0.3, show.legend = FALSE) 

journal_vs_data_availability

```


```{r}

journal_vs_analysis_a <- ggplot(data = interaction_data,
                             aes(x =  analysis,
                                 y = journal,
                                 color = journal)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_jitter(width = 0.3, show.legend = FALSE) 

journal_vs_analysis_a

```


```{r}

journal_vs_analysis_b <- ggplot(data = interaction_data,
                             aes(x =  analysis,
                                 y = journal,
                                 color = tests)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_jitter(width = 0.3, show.legend = FALSE) 

journal_vs_analysis_b


```


```{r}
journal_vs_analysis_c <- ggplot(data = interaction_data,
                             aes(x =  analysis,
                                 y = journal,
                                 color = design)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_jitter(width = 0.3, show.legend = FALSE) 

journal_vs_analysis_c

```


```{r}

journal_vs_design <- ggplot(data = interaction_data,
                             aes(x =  design,
                                 y = journal,
                                 color = journal)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_jitter(width = 0.3, show.legend = FALSE) 

journal_vs_design

```


```{r}
journal_vs_tests <- ggplot(data = interaction_data,
                             aes(x =  tests,
                                 y = journal,
                                 color = journal)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_jitter(width = 0.3, show.legend = FALSE) 

journal_vs_tests

```

```{r}

journal_vs_post_hoc <- ggplot(data = interaction_data,
                             aes(x =  post_hoc,
                                 y = journal,
                                 color = journal)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_jitter(width = 0.3, show.legend = FALSE) 

journal_vs_post_hoc

```


```{r}

journal_vs_t_tests <- ggplot(data = interaction_data,
                             aes(x =  t_tests,
                                 y = journal,
                                 color = journal)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_jitter(width = 0.3, show.legend = FALSE) 

journal_vs_t_tests

```


```{r}

design_vs_data_availability <- ggplot(data = interaction_data,
                             aes(x =  data_availability,
                                 y = design,
                                 color = journal)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_jitter(width = 0.3, show.legend = FALSE) 

design_vs_data_availability 

```


```{r}

analysis_vs_data_availability <- ggplot(data = interaction_data,
                             aes(x =  data_availability,
                                 y = analysis,
                                 color = journal)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_jitter(width = 0.3, show.legend = FALSE) 

analysis_vs_data_availability 
```


```{r}

tests_vs_data_availability <- ggplot(data = interaction_data,
                             aes(x =  data_availability,
                                 y = tests,
                                 color = journal)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_jitter(width = 0.3, show.legend = FALSE) 

tests_vs_data_availability 

```

```{r}

post_hoc_vs_data_availability <- ggplot(data = interaction_data,
                             aes(x =  data_availability,
                                 y = post_hoc,
                                 color = journal)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_jitter(width = 0.3, show.legend = FALSE) 

post_hoc_vs_data_availability 

```


```{r}

t_tests_vs_data_availability <- ggplot(data = interaction_data,
                             aes(x =  data_availability,
                                 y = t_tests,
                                 color = journal)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_jitter(width = 0.3, show.legend = FALSE) 

t_tests_vs_data_availability 

```


```{r}

design_vs_analysis_a <- ggplot(data = interaction_data,
                             aes(x =  analysis,
                                 y = design,
                                 color = journal)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_jitter(width = 0.3, show.legend = FALSE) 

design_vs_analysis_a
```


```{r}
design_vs_analysis_b <- ggplot(data = interaction_data,
                             aes(x =  analysis,
                                 y = design,
                                 color = tests)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_jitter(width = 0.3, show.legend = FALSE) 

design_vs_analysis_b

```


```{r}

design_vs_tests <- ggplot(data = interaction_data,
                             aes(x =  tests,
                                 y = design,
                                 color = journal)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_jitter(width = 0.3, show.legend = FALSE) 

design_vs_tests

```
```{r}
design_vs_post_hoc <- ggplot(data = interaction_data,
                             aes(x =  post_hoc,
                                 y = design,
                                 color = journal)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_jitter(width = 0.3, show.legend = FALSE) 

design_vs_post_hoc
```


```{r}

design_vs_t_tests <- ggplot(data = interaction_data,
                             aes(x =  t_tests,
                                 y = design,
                                 color = journal)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_jitter(width = 0.3, show.legend = FALSE) 

design_vs_t_tests


```


```{r}

tests_vs_analysis <- ggplot(data = interaction_data,
                             aes(x =  analysis,
                                 y = tests,
                                 color = journal)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_jitter(width = 0.3, show.legend = FALSE) 

tests_vs_analysis


```

```{r}

post_hoc_vs_analysis <- ggplot(data = interaction_data,
                             aes(x =  analysis,
                                 y = post_hoc,
                                 color = journal)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_jitter(width = 0.3, show.legend = FALSE) 

post_hoc_vs_analysis

```


```{r}

t_tests_vs_analysis <- ggplot(data = interaction_data,
                             aes(x =  analysis,
                                 y = t_tests,
                                 color = journal)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_jitter(width = 0.3, show.legend = FALSE) 

t_tests_vs_analysis

```


```{r}

tests_vs_t_tests <- ggplot(data = interaction_data,
                             aes(x =  t_tests,
                                 y = tests,
                                 color = journal)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_jitter(width = 0.3, show.legend = FALSE) 

tests_vs_t_tests


```

```{r}

post_hoc_vs_t_tests <- ggplot(data = interaction_data,
                             aes(x =  t_tests,
                                 y = post_hoc,
                                 color = journal)) +
  geom_point(alpha = 0.5, show.legend = FALSE) +
  geom_jitter(width = 0.3, show.legend = FALSE) 

post_hoc_vs_t_tests

```

